# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/message_service" # Location of package manifests
    open-pull-requests-limit: 10
    schedule:
      interval: "monthly"

#   - package-ecosystem: "npm"
#     directory: "/su_service"
#     open-pull-requests-limit: 10
#     schedule:
#       interval: "monthly"
