# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/auth_service" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/file_service" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/message_service" # Location of package manifests
    schedule:
      interval: "daily"
