[package]
name    = "file_service"
version = "0.1.0"
authors = ["Faster Speeding <luke@lmbyrne.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
    actix-web   = "4.0.0-beta.4"
    async-trait = "0.1.42"
    chrono      = "0.4.19"
 	log	        = "0.4.14"
    serde_json  = "1.0.59"

[dependencies.reqwest]
    features    = ["json"]
    version     = "0.11.2"

[dependencies.shared]
    path        = "../shared"
    features    = ["postgres"]

[dependencies.tokio]
    version     = "1.4.0"
    features    = ["macros", "rt"]  # "io-util", "stream"

[dependencies.uuid]
    version     = "0.8.2"
    features    = ["serde"]
