[package]
name    = "file_service"
version = "0.1.0"
authors = ["Faster Speeding <luke@lmbyrne.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
    actix-web       = "4.0.0-beta.4"
    # actix-web-httpauth = "0.5.1"  # TODO: when actix web 4.0.0 releases
    async-trait     = "0.1.42"
    base64          = "0.13.0"
    dotenv_codegen  = "0.15.0"
    log             = "0.4.14"
    serde           = "1.0.117"
    simple_logger   = "1.11.0"
    # sodiumoxide     = "0.2.6" TODO: use this or a different algorithm all together?

[dependencies.argonautica]
    version     = "0.2.0"
    features    = ["simd"]

[dependencies.sqlx]
    version     = "0.5.1"
    features    = ["chrono", "postgres", "runtime-tokio-native-tls", "uuid"]

[dependencies.tokio]
    version     = "1.4.0"
    features    = ["macros", "rt"]  # "io-util", "stream"

[dependencies.uuid]
    version     = "0.8.2"
    features    = ["serde"]
