[package]
name    = "file_service"
version = "0.1.0"
authors = ["Faster Speeding <luke@lmbyrne.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
    actix-web       = "4.0.0-beta.4"
    async-trait     = "0.1.42"
    dotenv_codegen  = "0.15.0"
    serde           = "1.0.117"
    log             = "0.4.14"
    simple_logger   = "1.11.0"

[dependencies.sqlx]
    features    = ["chrono", "postgres", "runtime-tokio-native-tls"]
    version     = "0.5.1"

[dependencies.tokio]
    version     = "1.4.0"
    features    = ["macros", "rt"]
